### get todos
GET http://localhost:8080/todos 

### get todo
GET http://localhost:8080/todos/97916b4f-6cbd-46d9-9743-db8afe6709ea

### add todo
POST http://localhost:8080/todos 
Content-Type: application/json

{ 
  "title" : "todo item",
  "completed": false
}

### delete todo
DELETE http://localhost:8080/todos/97916b4f-6cbd-46d9-9743-db8afe6709ea


### update todo
PUT http://localhost:8080/todos/97916b4f-6cbd-46d9-9743-db8afe6709ea
Content-Type: application/json

{ 
  "title" : "todo item update",
  "completed": true
}